<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Version>1.0.0</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SolarLab.EBoard.Posts.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SolarLab.EBoard.Posts.Application\SolarLab.EBoard.Posts.Application.csproj" />
      <ProjectReference Include="..\SolarLab.EBoard.Posts.Domain\SolarLab.EBoard.Posts.Domain.csproj" />
    </ItemGroup>

</Project>
